version: '2'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile-server
    volumes:
      - ./mrt:/var/opt/mrt

  client:
    build:
      context: ./
      dockerfile: Dockerfile-client
    depends_on:
      - server
    volumes:
      - ./mrt:/var/opt/mrt
