FROM alpine

ENV HOME /root
WORKDIR /root

RUN apk add --update supervisor && rm  -rf /tmp/* /var/cache/apk/*

ADD binary/gobgp /usr/bin/gobgp
ADD binary/gobgpd /usr/bin/gobgpd

ADD supervisord.conf /etc/supervisord.conf
ADD start-client-gobgpd /usr/bin/start-gobgpd
ENTRYPOINT ["/usr/bin/supervisord"]
