#!/bin/sh

IP=$(ip addr show eth0 | sed -nEe 's/^[ \t]*inet[ \t]*([0-9.]+)\/.*$/\1/p')
REMOTE=$(echo ${IP}|sed -nEe 's/(.[0-9]*)$/.2/p')
AS=$(echo ${IP}|awk -F '.' '{print $4}')

cat <<EOF > /etc/gobgpd.conf
[global.config]
as = "${AS}"
router-id = "${IP}"
[[neighbors]]
  [neighbors.config]
    peer-as = 65001
    neighbor-address = "${REMOTE}"
  [neighbors.timers.config]
    connect-retry = 1
    idle-hold-time-after-reset = 5
EOF

/usr/bin/gobgpd -f /etc/gobgpd.conf&
sleep 5
/usr/bin/gobgp mrt inject global /var/opt/mrt/rib.20190830.0800
/usr/bin/gobgp monitor neighbor
