#!/bin/sh

IP=$(ip addr show eth0 | sed -nEe 's/^[ \t]*inet[ \t]*([0-9.]+)\/.*$/\1/p')
REMOTE=$(echo ${IP}|sed -nEe 's/(.[0-9]*)$/.0\/24/p')

cat <<EOF > /etc/gobgpd.conf
[global.config]
as = 65001
router-id = "${IP}"
[global.apply-policy.config]
default-export-policy = "reject-route"
[[peer-groups]]
  [peer-groups.config]
    peer-group-name = "sample-group"
    peer-as = 0
[[dynamic-neighbors]]
  [dynamic-neighbors.config]
    prefix = "${REMOTE}"
    peer-group = "sample-group"
EOF

sleep 5
/usr/bin/watcher --setup-dynamic -p 8 -r 771684 > /var/log/watcher.log&
/usr/sbin/rustybgpd --perf
